# Generated by Django 2.2.2 on 2019-06-28 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginClaveUnica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.UUIDField(default=uuid.uuid4)),
                ('login_date', models.DateTimeField(auto_now_add=True)),
                ('authorization_code', models.CharField(max_length=120)),
                ('access_token', models.CharField(max_length=120)),
                ('remote_addr', models.CharField(max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Login Clave Unica',
            },
        ),
        migrations.CreateModel(
            name='PersonClaveUnica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_type', models.CharField(max_length=50)),
                ('run_num', models.IntegerField()),
                ('run_dv', models.CharField(max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
