# Generated by Django 2.2.2 on 2019-06-27 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clave_unica_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claveunicalogin',
            name='remote_addr',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
