# Generated by Django 2.2.2 on 2019-06-27 05:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clave_unica_auth', '0002_claveunicalogin_remote_addr'),
    ]

    operations = [
        migrations.AddField(
            model_name='claveunicalogin',
            name='login_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
