# Generated by Django 2.2.2 on 2019-07-07 21:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clave_unica_auth', '0004_auto_20190707_1720'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LoginClaveUnica',
            new_name='Login',
        ),
        migrations.RenameModel(
            old_name='PersonClaveUnica',
            new_name='Person',
        ),
    ]
