# Generated by Django 2.2.2 on 2019-07-07 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clave_unica_auth', '0005_auto_20190707_1738'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='login',
            options={'verbose_name_plural': 'Logins'},
        ),
    ]
