# Generated by Django 2.2.2 on 2019-07-07 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clave_unica_auth', '0003_loginclaveunica_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginclaveunica',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
