# Generated by Django 2.2.2 on 2019-07-08 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clave_unica_auth', '0006_auto_20190707_1808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='login',
            options={'verbose_name_plural': 'Login'},
        ),
    ]
